controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    dif_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dif_cont:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    wheels_per_side: 2
    wheel_separation: 1.4
    wheel_radius: 0.3

    use_stamped_vel: false